### ISSUE TITLE
lose itejms upon death

### ISSUE THREAD

**Issue by peanutinky** [SFort/MC-lapisreserve#1]
lose all items upon death they are not near where i last died at is there a fix for this

**Comment by SFort** [comment]
Are you playing with keepInventory on?
thats the only bug i managed to find simmilar to the one described
(also horribly sorry didnt see this earlier)

**Comment by SFort** [comment]
[lapisreserve-r1.0.3](https://github.com/SFort/MC-lapisreserve/releases/download/r1.0.3/lapisreserve-1.0.3.jar)
should fix it
edit: the new version is now also on curseforge

**Comment by SFort** [comment]
Assuming this is fixed
