### ISSUE TITLE
Can be marked as 1.19.3 compatible

### ISSUE THREAD

**Issue by sternschnaube** [SFort/MC-lapisreserve#10]
I was testing v1.0.8.

**Comment by SFort** [comment]
neat thanks,
just happened to have marked it yesterday though ;p
although thinking about it i'm guessing you're refering to the forge release which i forgot about...

**Comment by venaminecraft** [comment]
Modrinth, but I see that it's not there anymore 😕
(I was sure it was there, but I can be wrong.)
Thanks 😊

**Comment by SFort** [comment]
ye um sorry about that, several of my mods did used to be there but modrinth has a very very minor techical issue that annoys me and i ended up  being petty about it, if curse gives you trouble there's at least github releases
(and since i don't have publishing setup it's also less work for me ;p )

**Comment by venaminecraft** [comment]
Curse is really... a pain. If at least the search function + notification panel would work as it should be...
Modrinth got some bad changes as well. Sorry to hear that. Maybe in the future you can give it again a try.
I stay tuned with GitHub 😊
