### ISSUE TITLE
Lapis in the slot gets deleted.

### ISSUE THREAD

**Issue by DaddySpin** [SFort/MC-lapisreserve#2]
The lapis in the slot gets deleted for reasons i dont know. it could be dimension changes or server restarts/crashes.
i just want you to know this happens and i dont know why.

**Comment by SFort** [comment]
What mod version / minecraft version?
A list or zip of any other mods in use would also be helpfull since i currently can't reproduce the bug

**Comment by DaddySpin** [comment]
I can't reproduce this bug on demand, it mostly happens at random when i don't want it to.
Using 1.16.1 and lapisreserve-1.0.3
<details>
  <summary>Mod List</summary>

Fabric Mods: advancements-enlarger: Advancements Enlarger 0.2.2
               adventurez: AdventureZ 1.0.8
               allure: Allure 1.2.1
               amecs: Amecs 1.3.0+mc.1.16.1
               amecsapi: Amecs API 1.0.2+1.16-rc1
               angerable-patch: Angerable Patch 1.0.0-1.16.1
               appleskin: AppleSkin 1.0.11
               armorstandutils: Armor Stand Utils 1.0.1
               artifice: Artifice 0.8.1+1.16.1
               atmosfera: Atmosfera 1.2.2-1.16
               audiooutput: AudioOutput 0.0.2
               autoconfig1u: Auto Config v1 Updated 3.2.0-unstable
               battletowers: Battle Towers 3.0.3-beta-1.16.1
               bedrockwaters: BedrockWaters 1.3.0+1.16.1
               bedspreads: Bedspreads 1.0.0-1.16.1
               beenfo: Beenfo 1.16-fabric0.13.1-1.1.1
               better_wither_skeletons: Better Wither Skeletons 1.1.0
               bettereating: Better Eating 0.2.0
               betternether: Better Nether 3.5.4
               betterthanmending: BetterThanMending 1.2.0
               bigbuckets: Big Buckets 1.1.1
               blackstonetools: Blackstone Tools 1.2.0+1.16.1
               blockmeter: Block Meter 1.16.1-fabric0.14.1-1.4.4
               blue_endless_jankson: jankson +
               bunch-o-trinkets: Bunch O' Trinkets 1.0.1
               byg: BYG 1.0.13
               can-i-mine-this-block: can i mine this block? 1.0.0
               cardinal-components: Cardinal Components API 2.4.2
               cardinal-components-base: Cardinal Components API (base) 2.4.2
               cardinal-components-block: Cardinal Components API (blocks) 2.4.2
               cardinal-components-chunk: Cardinal Components API (chunks) 2.4.2
               cardinal-components-entity: Cardinal Components API (entities) 2.4.2
               cardinal-components-item: Cardinal Components API (items) 2.4.2
               cardinal-components-level: Cardinal Components API (world saves) 2.4.2
               cardinal-components-util: Cardinal Components API (utilities) 2.4.2
               cardinal-components-world: Cardinal Components API (worlds) 2.4.2
               cavebiomes: Cave Biomes 0.2.4
               chainmail: Chainmail 0.3.0
               chatcalc: ChatCalc 2.2
               cinderscapes: Cinderscapes 1.0.7+build.43-1.16.1
               cloth-basic-math: Cloth Basic Math 0.5.1
               cloth-client-events-v0: Cloth Client Events v0 1.0.4
               cloth-config2: Cloth Config v4 4.6.0
               com_squareup_moshi_moshi: moshi 1.9.2
               com_squareup_okio_okio: okio 1.16.0
               cotton-config: Cotton Config 1.0.0-rc.7
               cotton-logging: Cotton Logging 1.0.0-rc.4
               couplings: Couplings 1.3.1
               cr3stal: CrÂ³stal 1.0.0
               craftable_utilities: Craftable Utilities 1.0.1
               creativebuttonmover: Creative Button Mover 0.2.5
               crimsonmoon: Crimson Moon 1.2.2-1.16.1
               crookedcrooks: Crooked Crooks 1.2.1+1.16.1
               curioofundying: Curio of Undying 1.16.1-1.0
               curios: Curios API 1.16.1-0.5
               dark-loading-screen: Dark Loading Screen 1.4.2
               dontdropit: Don't Drop It! 1.3.1+1.16
               durabilityviewer: Giselbaers Durability Viewer 1.16-fabric0.13.1-1.8.1
               dynamicfps: Dynamic FPS 1.1.4
               dynamicsoundfilters: Dynamic Sound Filters 1.1.2+1.16.1
               earthtojavamobs: Earth2Java 1.1.0+1.16.1
               elytra_swap: Elytra Swap 2.1.0-1.16.1
               enchantablehorsearmor: Enchantable Horse Armor 1.0a
               enchantedbookredesign: Enchanted Book Redesign 1.0a
               enderitemod: Enderite Mod 1.1.3
               endreborn: End: Rebellion 1.6
               expandedstorage: ExpandedStorage 5.3.16
               experimentaway: ExperimentAway 1.0.0
               extrapieces: Extra Pieces 2.9.0
               fabric: Fabric API 0.17.0+build.386-1.16.1
               fabric-api-base: Fabric API Base 0.1.3+12a8474cb0
               fabric-biomes-v1: Fabric Biomes (v1) 0.2.7+059ea86602
               fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea8902
               fabric-command-api-v1: Fabric Command API (v1) 1.0.8+5ce5339802
               fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d3083602
               fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f02
               fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea86602
               fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d02
               fabric-dimensions-v1: fabric-dimensions-v1 1.0.0+a71b305302
               fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.3.3+7066030fb0
               fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b02
               fabric-furnaces: Fabric Furnaces 1.3.1-1.16.1
               fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.0+fe81e12502
               fabric-item-api-v1: Fabric Item API (v1) 1.0.0+16acbe5b02
               fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.0+438f963602
               fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+f404f3be02
               fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c5b0
               fabric-language-kotlin: Fabric Language Kotlin 1.3.72+build.1
               fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+e83e061c02
               fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.0+386eb69e02
               fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce9902
               fabric-models-v0: Fabric Models (v0) 0.1.0+dfdb52d602
               fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b02
               fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f02
               fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.5.7+2242e77202
               fabric-object-builders-v0: Fabric Object Builders (v0) 0.6.1+a2d21ddd02
               fabric-particles-v1: fabric-particles-v1 0.2.1+0a6f2a7002
               fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.3.8+7dba2d6c02
               fabric-renderer-api-v1: Fabric Renderer API (v1) 0.2.13+eae12eb802
               fabric-renderer-indigo: Fabric Renderer - Indigo 0.3.4+34d6c87102
               fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.1.0+be551d3c02
               fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.3+b7f9825d02
               fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.8+b7084faa02
               fabric-rendering-v0: Fabric Rendering (v0) 1.1.0+5341049002
               fabric-rendering-v1: Fabric Rendering (v1) 1.1.2+346247d702
               fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.2.6+f41e209802
               fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+97324d1102
               fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 0.2.7+a4c57d8e02
               fabric-textures-v0: Fabric Textures (v0) 1.0.4+eae12eb802
               fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.1+91fca5cd02
               fabricloader: Fabric Loader 0.9.0+build.204
               fastbench: FastBench 2.3
               fastfurnace: FastFurnace 2.2
               fatxporbs: Fat Experience Orbs 0.0.7
               fiber: fiber 0.23.0-2
               fullbellysheep: Full Belly Sheep 1.1.0
               gbfabrictools: GBfabrictools 1.2.2+1.16
               godown: Go Down 0.2.0+1.16.1
               grindenchantments: Grind Enchantments 1.1.1+1.16.1
               healthoverlay: Health Overlay 3.6.12
               hollowlogs: Hollow Logs 1.1.0
               horseinfo: Horse Info 0.2.2-1.16.1
               horsestatsvanilla: Horse Stats Vanilla 3.0.0
               iamverysmart: I Am Very Smart 2.1.0+mc1.16.1
               illuminations: Illuminations 1.0.4
               infinityfix: Infinity Fix 1.1.0
               inventoryprofiles: Inventory Profiles 0.4.2
               inventorytabs: Inventory Tabs 0.2.1-1.16.1
               itemmodelfix: Item Model Fix 0.1.1
               jankson: Jankson 3.0.0+j1.2.0
               kibe: Kibe 1.1.12-BETA
               kubejs: KubeJS 1.1.5
               kyrptconfig: Kytpt Config 1.0.4-1.16
               lakeside: Lakeside 1.0.2+1.16.1
               lambdynlights: LambDynamicLights 1.2.2+1.16.1
               lapisreserve: Lapis Reserve 1.0.3
               leaf-decay: Leaf Decay 1.2.0-1.16.1
               libcd: LibCapableData 2.5.0+1.16.1
               libgui: LibGui 2.3.0+1.16.1
               library_of_exile: Library of Exile 1.0.1
               libstructure: Libstructure 1.3
               lightoverlay: Light Overlay 5.4.1
               linkedstorage: Linked Storage 1.3.5-1.16
               lionutils: LionUtils 2.0.2+1.16
               litematica: Litematica 0.0.0-dev.20200711.162756
               lithium: Lithium 0.5.1
               llamasteeds: Llama Steeds 2020.2.8
               loadcatcher: Entrypoint Catcher 2.0.0
               lvmnt: SuperAxes 1.1.4
               magna: Magna 1.3.2-1.16.1
               malilib: MaLiLib 0.10.0-dev.21+arne.1
               mattocks: Mattocks 1.0.3
               minecraft: Minecraft 1.16.1
               minihud: MiniHUD 0.19.0-dev.20200701.005153
               missingbits: Missing Bits v1.16.1 Fabric b2
               mobz: MobZ 2.4.4
               modmenu: Mod Menu 1.14.5+build.30
               modupdater: ModUpdater 1.1.9+1.16.1
               mooblooms: Mooblooms 1.3.1
               morecraftingtables: Oh, How the Crafting Has Tabled! 0.1.0
               morepaths: More Paths 0.0.2
               mousewheelie: Mouse Wheelie 1.5.0+mc1.16.1
               muffle: Muffle 0.1.0
               nbtcrafting: NBT Crafting 2.0.0-beta.1+mc1.16.1
               netheritehorsearmor: Netherite Horse Armor 0.3.2
               ninjaphenix-container-lib: NinjaPhenix's Container Library 1.1.5
               nomoreglowingpots: No More Glowing Pots 1.0.2
               notenoughcrashes: Not Enough Crashes 2.1.4+1.16.1
               now-playing: Now Playing 1.1.3
               onsoulfire: On Soul Fire r4
               org_jetbrains_annotations: annotations 17.0.0
               org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.3.72
               org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.3.72
               org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.3.72
               org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.3.72
               org_jetbrains_kotlinx_kotlinx-coroutines-core: kotlinx-coroutines-core 1.3.7
               org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.3.7
               overloadedarmorbar: Overloaded Armor Bar 5.0.0-fabric
               p3utils: P3NG00's Utilities 0.0.0
               paintingcycle: Painting Cycle 1.0.0
               parchment: Parchment 1.0.2+1.15.2
               phosphor: Phosphor 0.6.0+build.7
               playerabilitylib: Pal 1.2.0
               portaltags: Portal Tags 1.0.0+1.16.1
               potionofbees: Potion Of Bees 1.0.1
               pumice: Pumice 0.0.1
               quickshulker: Quick Shulker 1.1.5-1.16
               reach-entity-attributes: Reach Entity Attribute 1.0.1
               repurposed_structures: Repurposed Structures 1.4.3
               respawnablepets: Respawnable Pets 4
               right-click-clear: Right Click Clear 2.0.2
               riverredux: River Redux 0.1.4
               roughlyenoughitems: Roughly Enough Items 4.11.0
               roughlyenoughresources: Roughly Enough Resources 2.0.2
               satin: Satin 1.4.0-nightly.1.16-pre5+build.1
               shapes: Shapes 2.0.0+build.10
               sheepconsistency: Sheep Consistency 1.0.2
               shieldisruptor: Shield Disruptor 1.0.1
               shulkerboxtooltip: Shulker Box Tootip 2.1.0+1.16.1
               simpleaccessories: Simple Accessories 0.2.0
               simpledrawers: Simple Drawers 1.8.0-1.16.1
               slightlyvanilla: SlightlyVanilla 1.0.9+1.16.1
               smb: Better Mod Button 1.1.4
               smoothscrollingeverywhere: Smooth Scrolling Everywhere 3.0.3-unstable
               soaring-clouds: Soaring Clouds 1.2.0-1.16
               sodium: Sodium 0.1.0
               soulbound: Soulbound 1.0.1
               soulsoilfarmland: Soul Soil Farmland 0.0.1
               speedtrading: Speed Trading 1.1.0+1.16
               spinnery: Spinnery 3.1.13
               spruceui: SpruceUI 1.5.8
               static-content: Static Content 1.0.0-1.16.1
               staticdata: Static Data 1.1.2
               step-height-entity-attribute: Step Height Entity Attribute 1.0.0
               storagecabinet: Storage Cabinet 1.1.2
               strongandfairanvils: Strong and Fair Anvils 0.3.0+1.16
               structure-helpers: Structure Helpers 2.1.0
               suitablystackablestew: Suitably Stackable Stew 1.1.0
               terraform: Terraform 2.1.7+build.31
               tinyfuel: Tiny Fuel 0.3.0
               torridvision: Torrid Vision 0.0.1
               trinkets: Trinkets 2.6.4
               trumpet-skeleton: Trumpet Skeleton 1.1.2
               tweed: Tweed API 3.0.0-beta.9
               vanilla-hammers: Vanilla Hammers 2.0.4-1.16.1
               vanillaexcavators: Vanilla Excavators 1.1.0
               waila: Hwyla 1.9.22
               wands: Wands Mod 1.1
               wolveswitharmor: Wolves With Armor 1.5.1-1.16.1
               xaerominimap: Xaero's Minimap 20.19.0
               xaeroworldmap: Xaero's World Map 1.9.0
</details>

**Comment by SFort** [comment]
[LapisReserve  rc1.0.4](https://github.com/SFort/MC-lapisreserve/releases/download/rc1.0.4/lapisreserve-1.0.4.jar)
Is an atempt to guess what could be going wrong since i still can't reproduce the issue
please see if it solves it

**Comment by SFort** [comment]
[LapisReserve pr1.0.5](https://github.com/SFort/MC-lapisreserve/releases/download/pr1.0.5/lapisreserve-1.0.5.jar)
Is and atempt to fix this (I haven't been able to reproduce the bug)
so please see if this fixes it for you
