### ISSUE TITLE
Not working without Fabric

### ISSUE THREAD

**Issue by Zygus42** [SFort/MC-lapisreserve#4]
v1.06 has the note: "no longer needs FabricAPI".

BUT, on startup using forge-1.16.4-35.1.29 I get the msg "file lapisreserve-1.0.6 is a Fabric mod and cannot be loaded".

**Comment by SFort** [comment]
"fabric modloader" and "fabricAPI" are two diffrent things.
also that version is still tagged for fabric.
someone ported the mod to forge it should be in the curse description i recommend you use that.
sorry for the confusion

**Comment by SFort** [comment]
however the port by reo-ar does add re-rolling enchants which you might not want  so i might look into making a forge version when i have the time

**Comment by SFort** [comment]
[Forge port](https://github.com/SFort/MC-lapisreserve/releases/download/r1.0.6/lapisreserve-1.0.6Forge.jar)
