### ISSUE TITLE
Add option

### ISSUE THREAD

**Issue by Psychodeus** [SFort/MC-lapisreserve#9]
Please add option to either reserve LL for all enchanting table or not (not behave like ender chest). Thanks.

**Comment by SFort** [comment]
it would be jank, the current mod is really simple and i just don't feel like adding a config to the mod

**Comment by Psychodeus** [comment]
But I'm using it in Singleplayer only. Can you still do that for me?
![pweeese](https://user-images.githubusercontent.com/93028949/196513540-11891253-5c3d-4d7b-b06f-817751d73024.png)

**Comment by SFort** [comment]
which mc version / mod loader?
i'll see if i can quickly throw it together so it's a maybe, even if though this will be jank in multiplayer

**Comment by Psychodeus** [comment]
MC Ver 1.19.2
Fabric Loader 0.14.9

Thank youuu

**Comment by SFort** [comment]
[mod.zip](https://github.com/SFort/MC-lapisreserve/files/9815314/mod.zip)
(github doesn't allow uploading jar file in comments and i don't wanna release this buggy thing anywhere else, so you'll have to unzip it)

**Comment by Psychodeus** [comment]
Thank you so much!
![aYJ5eADZ_700w_0](https://user-images.githubusercontent.com/93028949/196553179-c7836ae0-3043-4af3-abc9-e64584f1ee2c.jpg)
